### ISSUE TITLE
There is no such constructor as L.Toolbar.Control in the examples

### ISSUE THREAD

**Issue by joshting** [Leaflet/Leaflet.toolbar#36] opened 2016-01-14 06:35 UTC
I am trying to add customer toolbar and try out by using the given examples.  It doesn't work as there isn't such function as L.Toolbar.Control in the code?

Calling L.toolbar.control in turns call L.Toolbar.Control which doesn't help either.

Am I missing something here?

**Comment by camlani** [comment] 2016-02-09 15:22
I am having the same problem, as well

**Comment by justinmanley** [comment] 2016-03-04 04:01
This is a duplicate of #8.

**Closed by justinmanley** 2016-03-04 04:01 UTC
Labels: duplicate
